//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnketHazirlamaProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorular
    {
        public int SorId { get; set; }
        public int SorAnkId { get; set; }
        public string C1_Soru { get; set; }
        public string C2_Soru { get; set; }
        public string C3_Soru { get; set; }
    
        public virtual Anketler Anketler { get; set; }
    }
}
